name: Homsai Engine
version: "0.0.1"
slug: homsai
description: Add on that exposes the homsai magic to home assistant
url: https://github.com/HOMSAI-Smart-Home/HOMSAI-Add-on
codenotary: hello@homsai.app
init: false
hassio_api: true
homeassistant_api: true
ingress: true
auth_api: true
ingress_port: 8099
ports:
  8099/tcp: 8099
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
